const ActionTypes = {
    FILE_SUBMIT_PENDING:'FILE_SUBMIT_PENDING',
    FILE_SUBMIT_SUCCESS:'FILE_SUBMIT_SUCCESS',
    FILE_SUBMIT_REJECTED:'FILE_SUBMIT_PENDING',
    PROJECT_DATA_SUBMITTED:'PROJECT_DATA_SUBMITTED',
    IMAGE_LABEL_DATA_CHANGE:'IMAGE_LABEL_DATA_CHANGE'
}

export default ActionTypes;